<?php
return [
	"bbm" => "BBM",
	"bbw" => "BBW",
	"bdsm" => "BDSM",
	"bl" => "BL",
	"bss" => "BSS",
	"cg set" => "CG Set",
	"fffm foursome" => "FFFM Foursome",
	"ffm threesome" => "FFM Threesome",
	"mmf threesome" => "MMF Threesome",
	"mmmf foursome" => "MMMF Foursome",
	"romance-centric" => "Romance-centric",
	"slice of life" => "Slice of Life",
	"valentine-sale" => "Valentine-sale",
	"x-ray" => "X-ray",

	"first time" => "Defloration",
	"loli" => "Lolicon",
	"no sex" => "No Penetration",
	"ntr" => "Netorare",
	"public hair" => "Pubic Hair",
	"schoolgirl outfit" => "Schoolgirl Uniform",
	"shota" => "Shotacon",
	"creampie" => "Nakadashi",
	"big dick" => "Big Penis",
	"paperback" => "Tankoubon",
	"forced" => "Rape",
];
